export class editData {
  constructor() {
    this.hotelName = ''
    this.hotelEnName = ''
    this.cityId = ''
    this.cityName = ''
    this.groupId = ''
    this.hotelImg = '/cms/img/hotel_data/logo_default.png'
    this.ipAddr = ''
    this.hotelPort = '9000'
    this.uploadPort = '9001'
    this.isGrp = '1'
    this.hotelLeve = ''
    this.hotelStatus = ''
    this.contactor = ''
    this.phone = ''
    this.addr = ''
    this.email = ''
    this.fax = ''
    this.roomNum = ''
    this.terminalNum = ''
    this.secureKey = ''
    this.devType = ''
    this.devType1 = ''
    this.devType2 = ''
    this.hotelDesc = ''
    this.templateId = ''
    this.existentHotelId = ''
    this.configFile = ''
    this.code = ''
    this.updateId = ''
    this.langIds = ''
    this.longitude = ''
    this.latitude = ''
    this.sketch = ''
  }
}